services:
  dbt-dev:
    build:
      context: .
      target: dev
    environment:
      - DBT_ENV=dev
      - DEFAULT_DATASET=trips_data_all
      - LOCATION=asia-south1
      - DBT_PROJECT=eastern-amp-449614-e1
    volumes:
      - type: bind
        source: .
        target: /home/dbtuser/project
      - type: bind
        source: E:\.config\gcloud\application_default_credentials.json
        target: /home/dbtuser/.config/gcloud/application_default_credentials.json
        read_only: true
    ports:
      - "8080:8080"
    working_dir: /home/dbtuser/project
    entrypoint: ["/bin/bash"]
    tty: true
    stdin_open: true

  dbt-prod:
    build:
      context: .
      target: prod
    environment:
      - DBT_ENV=prod
      - DEFAULT_DATASET=trips_data_all_prod
      - LOCATION=asia-south1
      - DBT_PROJECT=eastern-amp-449614-e1
    volumes:
      - type: bind
        source: .
        target: /home/dbtuser/project
      - type: bind
        source: E:\.config\gcloud\application_default_credentials.json
        target: /home/dbtuser/.config/gcloud/application_default_credentials.json
        read_only: true
    ports:
      - "8081:8081" 
    working_dir: /home/dbtuser/project
    entrypoint: ["/bin/bash"]
    command: >
      -c "
      dbt debug --target prod &&
      dbt deps &&
      dbt seed --target prod &&
      dbt run --target prod &&
      dbt test --target prod &&
      dbt docs generate --target prod &&
      dbt docs serve --port 8081 
      "


