default:
  target: dev

  outputs:

    dev:
      type: bigquery
      method: oauth
      project: eastern-amp-449614-e1
      dataset: trips_data_all
      timeout_seconds: 300
      location: asia-south1
      priority: interactive
      retries: 0
      threads: 8

    prod:
      type: bigquery
      method: oauth
      project: eastern-amp-449614-e1
      dataset: trips_data_all_prod
      timeout_seconds: 300
      location: asia-south1
      priority: interactive
      retries: 1
      threads: 12