name: DBT CI

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  dbt-test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Desktop
      run: |
        # Docker Desktop should be pre-installed on Windows runners
        docker info

    - name: Build and run dbt tests
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      shell: cmd
      run: |
        :: Create credentials directory and file
        mkdir "%USERPROFILE%\.config\gcloud" 2>NUL
        echo %GCP_CREDENTIALS% > "%USERPROFILE%\.config\gcloud\application_default_credentials.json"
        
        :: Build and run tests in docker
        docker compose build dbt-dev
        docker compose run --rm ^
          -v "%USERPROFILE%\.config\gcloud:C:\Users\ContainerAdministrator\.config\gcloud" ^
          dbt-dev /bin/bash -c ^
          "dbt debug && ^
           dbt deps && ^
           dbt seed && ^
           dbt compile --target dev && ^
           dbt test --target dev"

  dbt-docs:
    runs-on: windows-latest
    needs: dbt-test
    
    steps:
    - uses: actions/checkout@v3

    - name: Generate DBT docs
      shell: cmd
      run: |
        docker compose run --rm dbt-dev /bin/bash -c ^
          "dbt deps && ^
           dbt seed && ^
           dbt docs generate"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: dbt-docs
        path: target/