name: DBT CI

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and run dbt tests
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        # Create credentials directory and file
        mkdir -p ~/.config/gcloud
        echo "$GCP_CREDENTIALS" > ~/.config/gcloud/application_default_credentials.json
        
        # Build and run tests in docker
        docker compose build dbt-dev
        docker compose run --rm \
          -v ~/.config/gcloud:/home/dbtuser/.config/gcloud \
          dbt-dev /bin/bash -c "
            dbt debug && \
            dbt deps && \
            dbt seed && \
            dbt compile --target dev && \
            dbt test --target dev"

  dbt-docs:
    runs-on: ubuntu-latest
    needs: dbt-test
    
    steps:
    - uses: actions/checkout@v3

    - name: Generate DBT docs
      run: |
        docker compose run --rm dbt-dev /bin/bash -c "
          dbt deps && \
          dbt seed && \
          dbt docs generate"

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: dbt-docs
        path: target/