name: DBT CI

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run dbt tests
      env:
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: |
        # Create credentials file
        echo "$GCP_CREDENTIALS" > /tmp/gcp-credentials.json
        
        # Build and run tests in docker
        docker compose build dbt-dev
        docker compose run --rm \
          -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json \
          dbt-dev /bin/bash -c "
            dbt deps && \
            dbt compile --target dev && \
            dbt test --target dev
          "

  dbt-docs:
    runs-on: ubuntu-latest
    needs: dbt-test
    
    steps:
    - uses: actions/checkout@v3

    - name: Generate DBT docs
      run: |
        docker compose run --rm dbt-dev /bin/bash -c "
          dbt deps && \
          dbt docs generate
        "

    - name: Upload docs artifact
      uses: actions/upload-artifact@v3
      with:
        name: dbt-docs
        path: target/ 