name: dbt CI

on:
  pull_request:
    branches:
      - main

jobs:
  dbt-ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run dbt container
        run: |
          docker build -t dbt-ci -f Dockerfile.dev .
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -v ${{ github.workspace }}/.dbt:/root/.dbt \
            -e DBT_PROFILES_DIR=/root/.dbt \
            -e DBT_PROJECT_DIR=/usr/app \
            dbt-ci dbt debug

      - name: Run dbt tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -v ${{ github.workspace }}/.dbt:/root/.dbt \
            -e DBT_PROFILES_DIR=/root/.dbt \
            -e DBT_PROJECT_DIR=/usr/app \
            dbt-ci dbt test

      - name: Run dbt build
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/usr/app \
            -v ${{ github.workspace }}/.dbt:/root/.dbt \
            -e DBT_PROFILES_DIR=/root/.dbt \
            -e DBT_PROJECT_DIR=/usr/app \
            dbt-ci dbt build
